### PR TITLE
Add support for querying the Clearbit combined enrichment API

### PR DESCRIPTION
**Pull request by cp**
This PR adds support for Clearbit's [combined API](https://clearbit.com/docs?javascript#enrichment-api-combined-api), which enabled you to enrich both company and person info using a single email address.

### CODE REVIEW

**Comment by cp** [comment]
@croaky Hmm, I'm not sure as I haven't used the CLI. Based on what I found [here](https://github.com/thoughtbot/clearbit/blob/master/cmd/clearbit/enrich.go#L39-L43), though, the CLI determines how we want to enrich based on the `@`, like you said. So if it's an email, we just enrich person data... but there's no way to get the combined data that this PR introduces.

Any ideas for an interface for fetching combined data? maybe a `--combined` flag to grab both person and company data?

**Comment by croaky** [comment]
> maybe a --combined flag to grab both person and company data?

That makes sense to me!

**Comment by cp** [comment]
@croaky Great, I pushed that functionality up.

**Comment by cp** [comment]
@croaky Wanted to ping you on this. Please let me know if there any other changes I should make.

**Comment by croaky** [comment]
Thank you! Merged. Sorry for the delay.

**Pull request closed without merging**
